### PR TITLE
Use config

### PR DESCRIPTION
**Pull request by vlados**

### CODE REVIEW

**Comment by pxlrbt** [comment]
Thanks for your PR. What's the benefit of using a config file? I guess I prefer the way via the service provider.

**Comment by vlados** [comment]
With config file - it will be cached like with the views, and it can be optimized when using opcache for example

**Comment by pxlrbt** [comment]
> With config file - it will be cached like with the views

I don't think that's a big benefit and shouldn't affect performance much.

> and it can be optimized when using opcache for example

OPCache should also apply for ServiceProviders.

**Comment by vlados** [comment]
This how every package for laravel works ...

**Pull request closed without merging**
